apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-envs-api
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-envs-api
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","list","create"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","create","update","patch","delete"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get","update","patch"]

  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","list","create","update","patch","delete"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch"]

  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get","list","create","update","patch","delete"]

  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-envs-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev-envs-api
subjects:
  - kind: ServiceAccount
    name: dev-envs-api
    namespace: dev