apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-test
  labels:
    app: sa-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sa-test
  template:
    metadata:
      labels:
        app: sa-test
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: toolbox
          image: docker.io/farisagianda/sa-test:v1
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - PYTHONDONTWRITEBYTECODE=1 python3 -m http.server 8080
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15