apiVersion: v1
kind: Service
metadata:
  name: sa-test
  namespace: sa-test
  labels:
    app: sa-test
spec:
  type: NodePort
  selector:
    app: sa-test
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080